### ISSUE TITLE
unpublish call on host causes to fire user-left event in remote audience

### ISSUE THREAD

**Issue by charlie-lk** [AgoraIO-Community/AgoraWebSDK-NG#11] opened 2020-05-26 16:51 UTC
Calling of the `unpublish` method in host fires the `users-unpublished` and `user-left` event in the "audience" remote users.

This is not documented in the SDK.

How to prevent the `user-left` event being fired in this scenario?

**Comment by disoul** [comment] 2020-05-27 06:43
Thanks for your feedback.

The `user-left` event was fired because we need to use this event to trigger the Agora Native SDK's decoder releasing. I think this is a bad design because this workaround will affect the customer's application logic. 

We are planning to solve it in `v0.2.0`,  just like #8 , we will redesign the unpublish mechanism in v0.2.0.

**Comment by charlie-lk** [comment] 2020-05-27 08:42
Thanks for the reply. Do you have any hints or suggestions on how applications can distinguish unpublishing and channel leaving at this point?

**Comment by disoul** [comment] 2020-05-27 11:27
There are two differences between unpublishing and leaving channel:
-  `user-left` event's `reason` param. If the remote peer is unpublished, `reason` will be `"BecomeAudience"`
- if this `user-left` event is caused by the remote peer unpublishing, you will receive `user-joined` about 10s after receiving `user-left`

So if you receive a `user-left` with `"BecomeAudience"` and receive `user-joined` in 10s, it is unpublishing, otherwise, it is channel leaving.

**Comment by charlie-lk** [comment] 2020-05-27 18:15
This definitely can address the application logic issues until the SDK v2 is brought out. 

In fact, `BecomeAudience` is enough for the application to change its state correctly and the subsequent `user-joined` is the lifesaver it can use.

Great patch!

**Comment by disoul** [comment] 2020-07-15 08:23
This issue has been fixed in `v4.0.0`( [release note](https://agoraio-community.github.io/AgoraWebSDK-NG/docs/en/release_note#fixed-issues))

**Closed by disoul** 2020-07-15 08:23 UTC
Labels: bug
